# Generated by Django 5.0.3 on 2024-03-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_customuser_date_joined_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
